baseURL = "/"
googleAnalytics = ""
languageCode = "en-gb"
title = "Portfolio"
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "rainbow_dash"
tabWidth = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "Articles"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[module.imports]]
path = "github.com/samrobbins85/hugo-developer-portfolio"
[params]
author = "Sam Robbins"
description = "The website of Manik Dhingra, Business Analyst at JP Morgan Chase"
home = "Home"
[params.contact]
enable = true
formAction = ""
[params.footer]
address = "New Jersey, USA"
email = "manik.analyst@gmail.com"
googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"
[[params.plugins.css]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
[[params.plugins.js]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
[[params.plugins.js]]
URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"
